apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-simple-java-app
  namespace: argocd
spec: 
  project: default

  source:
    path: ''
    repoURL: 'https://tranthang-2804.github.io/k8s-manifest-for-simple-java-app/'
    targetRevision: '*'
    chart: helm-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: thangtd18-application
  
  syncPolicy:
    syncOptions: 
      - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true