apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-simple-java-app
  namespace: argocd
spec: 
  project: default

  source:
    repoURL: https://github.com/TranThang-2804/k8s-manifest-for-simple-java-app.git
    targetRevision: HEAD
    path: /src
  destination:
    server: https://kubenetes.default.svc
    namespace: thangtd18-application
  
  syncPolicy:
    syncOptions: 
      - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true